version: '3.9'
services:
  postgres:
    image: postgres:16
    container_name: products_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME:-products_db}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres} -d ${DB_NAME:-products_db}"]
      interval: 5s
      timeout: 5s
      retries: 10
volumes:
  db_data: {}

